#!/bin/bash

set -x

# Generates an SVN-compatible diff against the tip of the tracking branch
#
# CONFIGURATION:
# * Drop this script in one of the directories listed in your PATH like '/usr/local/bin'
# * Add the following aliases in your gitconfig file (as an example - look at file gitconfig):
# branch-name = !git for-each-ref --format='%(refname:short)' `git symbolic-ref HEAD`
# cd-root = rev-parse --show-cdup
# svn-branch-patch = !git-svn-diff.sh > `git cd-root``git branch-name`.patch
#
# USAGE:
# $ git checkout [branch]
# $ git svn-branch-patch
# $ less `git cd-root``git branch-name`.patch
#
# https://gist.github.com/1449541/
#
# git-svn-diff.sh originally by (http://mojodna.net/2009/02/24/my-work-git-workflow.html)
# modified by mike@mikepearce.net
# modified by aconway@[redacted] - handle diffs that introduce new files
# modified by t.broyer@ltgt.net - fixes diffs that introduce new files
# modified by m@rkj.me - fix sed syntax issue in OS X
#

# Get the tracking branch (if we're on a branch)
TRACKING_BRANCH=`git svn info | grep URL | sed -e 's/.*\/branches\///'`
BRANCH_NAME=$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
DATE=$(date "+%Y%m%d")

# If the tracking branch has 'URL' at the beginning, then the sed wasn't successful and
# we'll fall back to the svn-remote config option
if [[ "$TRACKING_BRANCH" =~ URL.* ]]
then
        TRACKING_BRANCH=`git config --get svn-remote.svn.fetch | sed -e 's/.*:refs\/remotes\///'`
fi

#TRACKING_BRANCH="mirror/${TRACKING_BRANCH}"
echo "Tracking branch: ${TRACKING_BRANCH}"

# Get the highest revision number
REV=`git svn find-rev $(git rev-list --date-order --max-count=1 $TRACKING_BRANCH)`

# Then do the diff from the highest revision on the current branch 
# and masssage into SVN format
git diff --no-prefix $(git rev-list --date-order --max-count=1 $TRACKING_BRANCH) $* |
sed -e "/--- \/dev\/null/{ N; s|^--- /dev/null\n+++ \(.*\)|--- \1	(revision 0)\n+++ \1	(revision 0)|;}" \
    -e "s/^--- .*/&	(revision $REV)/" \
    -e "s/^+++ .*/&	(working copy)/" \
    -e "s/^diff --git [^[:space:]]*/Index:/" \
    -e "s/^index.*/===================================================================/"

